steps:
- name: 'gcr.io/google_containers/ubuntu-slim:0.14'
  args: ["sed", "-i", '/revisionId/c\   \"revisionId\": \"$COMMIT_SHA\",',"source-context.json"]

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/node-debug:${BRANCH_NAME}', '.']

images: ['gcr.io/$PROJECT_ID/node-debug']
